/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/auditLog': RouteRecordInfo<'/auditLog', '/auditLog', Record<never, never>, Record<never, never>>,
    '/forgotPassword': RouteRecordInfo<'/forgotPassword', '/forgotPassword', Record<never, never>, Record<never, never>>,
    '/formGenerator': RouteRecordInfo<'/formGenerator', '/formGenerator', Record<never, never>, Record<never, never>>,
    '/hardwareMaintenanceRecord': RouteRecordInfo<'/hardwareMaintenanceRecord', '/hardwareMaintenanceRecord', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/marketingAnalysis': RouteRecordInfo<'/marketingAnalysis', '/marketingAnalysis', Record<never, never>, Record<never, never>>,
    '/marketingBudgetManagement': RouteRecordInfo<'/marketingBudgetManagement', '/marketingBudgetManagement', Record<never, never>, Record<never, never>>,
    '/marketingCategoryManagement': RouteRecordInfo<'/marketingCategoryManagement', '/marketingCategoryManagement', Record<never, never>, Record<never, never>>,
    '/marketingExpenseManagement': RouteRecordInfo<'/marketingExpenseManagement', '/marketingExpenseManagement', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password/:token', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
  }
}
